ChatItUp/Models/ThreadPost.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ChatItUp.Models
{
    public class ThreadPost
    {
        [Key]
        public int ThreadPostId { get; set; }

        public string message { get; set; }

        [Required]
        public ApplicationUser user {get;set;}

        [Required]
        [DataType(DataType.Date)]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime dateCreatd { get; set; }

        public int ThreadId { get; set; }
        public Thread Thread { get; set; }

    }
}

ChatItUp/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ChatItUp.Data;
using ChatItUp.Models;

namespace ChatItUp.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Category.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .SingleOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryId")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category.SingleOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CategoryId")] Category category)
        {
            if (id != category.CategoryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CategoryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .SingleOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Category.SingleOrDefaultAsync(m => m.CategoryId == id);
            _context.Category.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool CategoryExists(int id)
        {
            return _context.Category.Any(e => e.CategoryId == id);
        }
    }
}

ChatItUp/Controllers/ForaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ChatItUp.Data;
using ChatItUp.Models;
using Microsoft.AspNetCore.Identity;

namespace ChatItUp.Controllers
{
    public class ForaController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ForaController(ApplicationDbContext context, UserManager<ApplicationUser> user)
        {
            _context = context;
            _userManager = user;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);
        // GET: Fora
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Forum.Include(f => f.Category);
            return View(await applicationDbContext.ToListAsync());
        }

        //GET: Forum/index/5
        public async Task<IActionResult> Index2(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var currentUser = await GetCurrentUserAsync();
            var forum = await _context.Forum.Where(f => f.CategoryId == id).ToListAsync();
            if(forum == null)
            {
                return NotFound();
            }
            return View(forum);
        }

        // GET: Fora/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forum = await _context.Forum
                .Include(f => f.Category)
                .SingleOrDefaultAsync(m => m.ForumId == id);
            if (forum == null)
            {
                return NotFound();
            }

            return View(forum);
        }

        // GET: Fora/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryId");
            return View();
        }

        // POST: Fora/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ForumId,ThreadTitles,CategoryId")] Forum forum)
        {
            if (ModelState.IsValid)
            {
                _context.Add(forum);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryId", forum.CategoryId);
            return View(forum);
        }

        // GET: Fora/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forum = await _context.Forum.SingleOrDefaultAsync(m => m.ForumId == id);
            if (forum == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryId", forum.CategoryId);
            return View(forum);
        }

        // POST: Fora/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ForumId,ThreadTitles,CategoryId")] Forum forum)
        {
            if (id != forum.ForumId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(forum);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ForumExists(forum.ForumId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryId", forum.CategoryId);
            return View(forum);
        }

        // GET: Fora/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forum = await _context.Forum
                .Include(f => f.Category)
                .SingleOrDefaultAsync(m => m.ForumId == id);
            if (forum == null)
            {
                return NotFound();
            }

            return View(forum);
        }

        // POST: Fora/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var forum = await _context.Forum.SingleOrDefaultAsync(m => m.ForumId == id);
            _context.Forum.Remove(forum);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool ForumExists(int id)
        {
            return _context.Forum.Any(e => e.ForumId == id);
        }
    }
}

ChatItUp/Controllers/ThreadsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ChatItUp.Data;
using ChatItUp.Models;
using ChatItUp.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace ChatItUp.Controllers
{
    public class ThreadsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ThreadsController(ApplicationDbContext context, UserManager<ApplicationUser> user)
        {
            _context = context;
            _userManager = user;
        }


        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: Threads
        public async Task<IActionResult> Index(int? id)
        {
            ThreadForumViewModel ThreadVM = new ThreadForumViewModel();
            if(id == null)
            {
                return NotFound();
            }

           ThreadVM.Thread =await _context.Thread.Include(t => t.Forum).Include(u => u.User).Where(f => f.ForumId == (int)id).ToListAsync();
            ThreadVM.Forum = _context.Forum.Include(t => t.thread).SingleOrDefault(m => m.ForumId == (int)id);

            return View(ThreadVM);
        }

        // GET: Threads/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var thread = await _context.Thread
                .Include(t => t.Forum)
                .SingleOrDefaultAsync(m => m.ThreadId == id);
            if (thread == null)
            {
                return NotFound();
            }

            return View(thread);
        }

        // GET: Threads/Create
        [Authorize]
        public async Task <IActionResult> Create(int? id)
        {
            var thread = new Thread();
            thread.ForumId = (int)id;
            var user = await GetCurrentUserAsync();
            ViewData["ForumId"] = new SelectList(_context.Forum, "ForumId", "ForumId");
            return View(thread);
        }

        // POST: Threads/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create(Thread thread)
        {
            ModelState.Remove("User");
            if (ModelState.IsValid)
            {
               
                var user = await GetCurrentUserAsync();
                thread.User = user;
                _context.Add(thread);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new {id= thread.ForumId });
            }
            ViewData["ForumId"] = new SelectList(_context.Forum, "ForumId", "ForumId", thread.Forum.ForumId);
            ThreadForumViewModel ThreadVM2 = new ThreadForumViewModel();
            return View(thread);
        }

        // GET: Threads/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var thread = await _context.Thread.SingleOrDefaultAsync(m => m.ThreadId == id);
            if (thread == null)
            {
                return NotFound();
            }
            ViewData["ForumId"] = new SelectList(_context.Forum, "ForumId", "ForumId", thread.ForumId);
            return View(thread);
        }

        // POST: Threads/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ThreadId,Title,ForumId,created")] Thread thread)
        {
            if (id != thread.ThreadId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(thread);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ThreadExists(thread.ThreadId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["ForumId"] = new SelectList(_context.Forum, "ForumId", "ForumId", thread.ForumId);
            return View(thread);
        }

        // GET: Threads/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var thread = await _context.Thread
                .Include(t => t.Forum)
                .SingleOrDefaultAsync(m => m.ThreadId == id);
            if (thread == null)
            {
                return NotFound();
            }

            return View(thread);
        }

        // POST: Threads/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var thread = await _context.Thread.SingleOrDefaultAsync(m => m.ThreadId == id);
            _context.Thread.Remove(thread);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool ThreadExists(int id)
        {
            return _context.Thread.Any(e => e.ThreadId == id);
        }
    }
}

ChatItUp/Views/ThreadPosts/Create.cshtml
@model ChatItUp.Models.ThreadPost

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>ThreadPost</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="message" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="message" class="form-control" />
                <span asp-validation-for="message" class="text-danger"></span>
            </div>
        </div>

        
        <input type="hidden" asp-for="ThreadId" />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ChatItUp/Views/ThreadPosts/Delete.cshtml
@model ChatItUp.Models.ThreadPost

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ThreadPost</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="ThreadPostId" />
        <dt>
            @Html.DisplayNameFor(model => model.message)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.message)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.dateCreatd)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.dateCreatd)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Thread)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Thread.ThreadId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

ChatItUp/Views/ThreadPosts/Details.cshtml
@model ChatItUp.Models.ThreadPost

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>ThreadPost</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.message)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.message)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.dateCreatd)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.dateCreatd)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Thread)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Thread.ThreadId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ThreadPostId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ChatItUp/Views/ThreadPosts/Edit.cshtml
@model ChatItUp.Models.ThreadPost

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>ThreadPost</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="ThreadPostId" />
        <div class="form-group">
            <label asp-for="message" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="message" class="form-control" />
                <span asp-validation-for="message" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="dateCreatd" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="dateCreatd" class="form-control" />
                <span asp-validation-for="dateCreatd" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ThreadId" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="ThreadId" class="form-control" asp-items="ViewBag.ThreadId"></select>
                <span asp-validation-for="ThreadId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ChatItUp/Views/ThreadPosts/Index.cshtml
@model ChatItUp.Models.ViewModels.ThreadPostIndexViewModel

@{
    ViewData["Title"] = "Index";
}

<h2>@Model.Thread.Title</h2>

<p><a asp-controller="Categories" asp-action="Index">Categories </a>: <a asp-controller="Fora" asp-action="Index2" asp-route-id="@Model.Forum.CategoryId">Forum</a> : <a asp-controller="Threads" asp-route-id="@Model.Thread.ForumId">Threads </a>: Discussion</p>


<p>
    <a asp-action="Create" asp-route-id="@Model.Thread.ThreadId">Reply</a>
</p>

<div class="container">
    <div class="row">
        <span class="col-md-3">By</span>

        <span class="col-md-4">Message</span>

        <span class="col-lg-4">Created on</span>
    </div>
</div>
<hr />
<div class="row">
    <div class="msg-update-boxes">
        <span class="col-md-3">
            <img src=" @Model.Thread.User.ProfileImage" alt="img" class="feedImg" />
            @Model.Thread.User.Firstname
            @Model.Thread.User.Lastname
        </span>
        <span class="col-md-4">
            @Model.Thread.AuthorMessage
        </span>
        <span class="col-md-4">
            @Model.Thread.created
        </span>
    </div>
</div>
<hr />
<br />
<br />



@foreach (var item in Model.threadpost)
{
<div class="row current-chat-area">
    <div class="col-md-12">
        <ul class="media-list">
            <li class="media">
                <div class="media-body">
                    <div class="media">
                        <a asp-controller="Relations" asp-action="UserProfile" asp-route-id="@item.user.Id" class="pull-left">
                            <img class="feedImg img-circle" src="@item.user.ProfileImage">
                        </a>
                        <div class="media-body">
                            @Html.DisplayFor(modelItem => item.message)
                            <br>
                            <small class="text-muted">@Html.DisplayFor(modelItem => item.user.Firstname)
                            @Html.DisplayFor(x => item.user.Lastname) | @Html.DisplayFor(modelItem => item.dateCreatd) | Reply</small>
                            <hr>
                        </div>
                    </div>
                </div>
            </li>
            </ul>
           </div>
    </div>
}