ChatItUp/Models/Relation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ChatItUp.Models
{
    public class Relation
    {
        [Key]
        public int RelationshipId { get; set; }

        [Required]
        public ApplicationUser User { get; set; }

        [Required]
        public ApplicationUser Friend { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime ConnectedOn { get; set; }

        public bool? Connected { get; set; }
    }
}

ChatItUp/Models/ViewModels/AddFriendViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ChatItUp.Models.ViewModels
{
    public class AddFriendViewModel
    {
        public ApplicationUser User { get; set; }

        public List<Relation> relation { get; set; }
    }
}

ChatItUp/Controllers/RelationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ChatItUp.Data;
using ChatItUp.Models;
using Microsoft.AspNetCore.Identity;
using ChatItUp.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace ChatItUp.Controllers
{
    public class RelationsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public RelationsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: Relations
        public async Task<IActionResult> Index()
        {
            return View(await _context.Relation.ToListAsync());
        }

        //GET: USER PROFILE
        public async Task<IActionResult> UserProfile(string id)
        {
            UserProfileViewModel upVM = new UserProfileViewModel();
            var user = await GetCurrentUserAsync();
            if(id == null)
            {
                return NotFound();
            }
            if(id == user.Id)
            {
                return RedirectToAction("Index", "Manage");
            }
            var userFriend = await _context.ApplicationUser.SingleOrDefaultAsync(x => x.Id == id);

            var CheckConnectedButNotConfirmed =  _context.Relation.Any(x => x.Friend == userFriend &&  x.User.Id == user.Id && x.Connected == null);

            var CheckConnectedAndConfirmed = _context.Relation.Any(x => x.Friend == userFriend && x.User.Id == user.Id && x.Connected == true);

            var CheckConnectedAndConfirmed2 = _context.Relation.Any(x => x.User == userFriend && x.Friend.Id == user.Id && x.Connected == true);
            var completeFriendList = await _context.Relation.Include("Friend").Where(x => x.User == user && x.Friend.Id==id && x.Connected == true).ToListAsync();
            var completeFriendList2 = await _context.Relation.Include("User").Where(x => x.Friend == user && x.User.Id==id && x.Connected == true).ToListAsync();
            var completeFriendList3 = await _context.Relation.Include("Friend").Where(x => x.User.Id == id && x.User!= user && x.Friend != user && x.Connected == true).ToListAsync();
            var completeFriendList4 = await _context.Relation.Include("User").Where(x => x.Friend.Id == id && x.User != user  && x.Friend != user && x.Connected == true).ToListAsync();

            var posts = _context.ThreadPost.Where(x => x.user.Id == id);

            var threadsCretaed = await _context.Thread.Where(x => x.User.Id == id).ToListAsync();

            upVM.checkconnectedbutnotconfirmed = CheckConnectedButNotConfirmed;
            upVM.checkConnectedAndConfirmed = CheckConnectedAndConfirmed;
            upVM.checkConnectedAndConfirmed2 = CheckConnectedAndConfirmed2;
            upVM.User = await _context.ApplicationUser.Where(u => u.Id == id).SingleOrDefaultAsync();
            upVM.friendList = completeFriendList;
            upVM.friendList2 = completeFriendList2;
            upVM.friendList3 = completeFriendList3;
            upVM.friendList4 = completeFriendList4;
            upVM.totalThreads = threadsCretaed;
            upVM.totalPosts = posts;            

            return View(upVM);
        }

        //AddFriend Post
        [HttpPost]
        public async Task<IActionResult> AddFriend(ApplicationUser user)
        {
            
            var currentUser = await GetCurrentUserAsync();
            if(currentUser == null)
            {
                return NotFound();
            }

            ApplicationUser userFriend = await _context.ApplicationUser.Where(u => u.Id == user.Id).SingleOrDefaultAsync();

            var relationB = new Relation() {User = currentUser, Friend = userFriend};



            _context.Add(relationB);
            await _context.SaveChangesAsync();


           return RedirectToAction("UserProfile", new {id= userFriend.Id });
        }



        //DELETEFRIEND POST
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> RemoveFriend(string id)
        {
            var currentUser = await GetCurrentUserAsync();
            if(currentUser == null)
            {
                return NotFound();
            }
            ApplicationUser userFriend = await _context.ApplicationUser.SingleOrDefaultAsync(x => x.Id == id);

            try
            {
            var UserIdIsCurrentUser = _context.Relation.Include("Friend").Single(x => x.User == currentUser && x.Friend.Id== id && x.Connected == true);
            if (UserIdIsCurrentUser != null)
            {
                _context.Remove(UserIdIsCurrentUser);
            }
            }
            catch
            {
            var friendIdIsYourFriend = _context.Relation.Single(x => x.User.Id == id && x.Friend== currentUser && x.Connected == true);
            if(friendIdIsYourFriend != null)
            {
                _context.Remove(friendIdIsYourFriend);
            }

            }
            

            

           
            await _context.SaveChangesAsync();
            return RedirectToAction("UserProfile", new { id = userFriend.Id });

        }



        // GET: Relations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var relation = await _context.Relation
                .SingleOrDefaultAsync(m => m.RelationshipId == id);
            if (relation == null)
            {
                return NotFound();
            }

            return View(relation);
        }

        // GET: Relations/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Relations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RelationshipId,connectedOn,connected")] Relation relation)
        {
            if (ModelState.IsValid)
            {
                _context.Add(relation);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(relation);
        }

        // GET: Relations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var relation = await _context.Relation.SingleOrDefaultAsync(m => m.RelationshipId == id);
            if (relation == null)
            {
                return NotFound();
            }
            return View(relation);
        }

        // POST: Relations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RelationshipId,connectedOn,connected")] Relation relation)
        {
            if (id != relation.RelationshipId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(relation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RelationExists(relation.RelationshipId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(relation);
        }

        // GET: Relations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var relation = await _context.Relation
                .SingleOrDefaultAsync(m => m.RelationshipId == id);
            if (relation == null)
            {
                return NotFound();
            }

            return View(relation);
        }

        // POST: Relations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var relation = await _context.Relation.SingleOrDefaultAsync(m => m.RelationshipId == id);
            _context.Relation.Remove(relation);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool RelationExists(int id)
        {
            return _context.Relation.Any(e => e.RelationshipId == id);
        }
    }
}

ChatItUp/Controllers/ThreadPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ChatItUp.Data;
using ChatItUp.Models;
using Microsoft.AspNetCore.Identity;
using ChatItUp.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace ChatItUp.Controllers
{
    public class ThreadPostsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ThreadPostsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: ThreadPosts
        public async Task<IActionResult> Index(int? id)
        {
            ThreadPostIndexViewModel ThreadPostVM = new ThreadPostIndexViewModel();

            if(id == null)
            {
                return NotFound();
            }
            ThreadPostVM.threadpost = await _context.ThreadPost.Include(t => t.Thread).Include(u => u.user).Where(tp => tp.ThreadId == (int)id).ToListAsync();

            ThreadPostVM.Thread =  _context.Thread.Include(t => t.ThreadPost).Include(u => u.User).SingleOrDefault(tp => tp.ThreadId == (int)id);


            ThreadPostVM.Forum = _context.Forum.Include(t => t.thread).SingleOrDefault(m => m.ForumId == ThreadPostVM.Thread.ForumId);
            

            return View(ThreadPostVM);
        }

        // GET: ThreadPosts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var threadPost = await _context.ThreadPost
                .Include(t => t.Thread)
                .SingleOrDefaultAsync(m => m.ThreadPostId == id);
            if (threadPost == null)
            {
                return NotFound();
            }

            return View(threadPost);
        }

        // GET: ThreadPosts/Create
        [Authorize]
        public async Task<IActionResult> Create(int? id)
        {
            var threadpost = new ThreadPost();
            threadpost.ThreadId = (int)id;

            var thread= await _context.Thread
                .Where(t => t.ThreadId == threadpost.ThreadId).ToListAsync();

            var user = await GetCurrentUserAsync();
            ViewData["ThreadId"] = new SelectList(_context.Thread, "ThreadId", "ThreadId");
            return View(threadpost);
        }

        // POST: ThreadPosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create(ThreadPost threadPost)
        {
            ModelState.Remove("User");
            if (ModelState.IsValid)
            {
                var user = await GetCurrentUserAsync();
                threadPost.user = user;
                _context.Add(threadPost);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { id = threadPost.ThreadId});
            }
            ViewData["ThreadId"] = new SelectList(_context.Thread, "ThreadId", "ThreadId", threadPost.ThreadId);
            return View(threadPost);
        }

        // GET: ThreadPosts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var threadPost = await _context.ThreadPost.SingleOrDefaultAsync(m => m.ThreadPostId == id);
            if (threadPost == null)
            {
                return NotFound();
            }
            ViewData["ThreadId"] = new SelectList(_context.Thread, "ThreadId", "ThreadId", threadPost.ThreadId);
            return View(threadPost);
        }

        // POST: ThreadPosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ThreadPostId,message,dateCreatd,ThreadId")] ThreadPost threadPost)
        {
            if (id != threadPost.ThreadPostId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(threadPost);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ThreadPostExists(threadPost.ThreadPostId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["ThreadId"] = new SelectList(_context.Thread, "ThreadId", "ThreadId", threadPost.ThreadId);
            return View(threadPost);
        }

        // GET: ThreadPosts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var threadPost = await _context.ThreadPost
                .Include(t => t.Thread)
                .SingleOrDefaultAsync(m => m.ThreadPostId == id);
            if (threadPost == null)
            {
                return NotFound();
            }

            return View(threadPost);
        }

        // POST: ThreadPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var threadPost = await _context.ThreadPost.SingleOrDefaultAsync(m => m.ThreadPostId == id);
            _context.ThreadPost.Remove(threadPost);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool ThreadPostExists(int id)
        {
            return _context.ThreadPost.Any(e => e.ThreadPostId == id);
        }
    }
}

ChatItUp/Views/Relations/AddFriend.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

ChatItUp/Views/Relations/Create.cshtml
@model ChatItUp.Models.Relation

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Relation</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="connectedOn" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="connectedOn" class="form-control" />
                <span asp-validation-for="connectedOn" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="connected" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="connected" class="form-control" />
                <span asp-validation-for="connected" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ChatItUp/Views/Relations/Delete.cshtml
@model ChatItUp.Models.Relation

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Relation</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="RelationshipId" />
        <dt>
            @Html.DisplayNameFor(model => model.connectedOn)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.connectedOn)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.connected)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.connected)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

ChatItUp/Views/Relations/Details.cshtml
@model ChatItUp.Models.Relation

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Relation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.connectedOn)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.connectedOn)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.connected)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.connected)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.RelationshipId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ChatItUp/Views/Relations/Edit.cshtml
@model ChatItUp.Models.Relation

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Relation</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="RelationshipId" />
        <div class="form-group">
            <label asp-for="connectedOn" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="connectedOn" class="form-control" />
                <span asp-validation-for="connectedOn" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="connected" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="connected" class="form-control" />
                <span asp-validation-for="connected" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ChatItUp/Views/Relations/Index.cshtml
@model IEnumerable<ChatItUp.Models.Relation>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.connectedOn)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.connected)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.connectedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.connected)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.RelationshipId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.RelationshipId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.RelationshipId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

ChatItUp/Views/Relations/UserProfile.cshtml
@model ChatItUp.Models.ViewModels.UserProfileViewModel



<p class="text-success">@ViewData["StatusMessage"]</p>

<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
<div class="container">
    <div class="fb-profile">
        @if (Model.User.BannerImage == null)
        {
           <img align = "left" class="fb-image-lg" src="~/Profile/blankBanner.jpg" alt="blank banner" />
        }
        else
        {
        <img align="left" class="fb-image-lg" src="@Model.User.BannerImage" alt="Profile image example" />
        }
        @if (Model.User.ProfileImage == null)
        {
            <img align="left" class="fb-image-profile thumbnail" src="~/Profile/blankProfile.jpg" alt="blank profile image" />
        }
        else
        {
        <img align="left" class="fb-image-profile thumbnail" src="@Model.User.ProfileImage" alt="Profile image example" />
        }
        <div class="fb-profile-text">
            <h1>@Model.User.Firstname @Model.User.Lastname</h1>
            @if (Model.checkconnectedbutnotconfirmed)
            {

                 <button type="submit" class="btn btn-default" disabled>Request Sent</button>
            }
            @if (Model.checkConnectedAndConfirmed)
            {
                <form asp-method="post" asp-action="RemoveFriend" asp-controller="Relations">
                    <input type="hidden" value="@Model.User.Id" name="id" />
                    <button type="submit" class="btn btn-default">Remove</button>
                </form>
            }
            @if (Model.checkConnectedAndConfirmed2)
            {
                <form asp-method="post" asp-action="RemoveFriend" asp-controller="Relations">
                    <input type="hidden" value="@Model.User.Id" name="id" />
                    <button type="submit" class="btn btn-default">Remove</button>
                </form>
            }
            @if (Model.checkConnectedAndConfirmed == false && Model.checkConnectedAndConfirmed2 == false && Model.checkconnectedbutnotconfirmed == false)
            {
            <form asp-method="post" asp-action="AddFriend" asp-controller="Relations">
                    <input type="hidden" asp-for="@Model.User.Id" />
                    <button type="submit" class="btn btn-default">Add</button>
            </form> 
            }
            <div class="col-sm-4 offset-lg-5 scrolling">
                <div>
                    <h4>Friends     </h4>
                    @foreach (var item in Model.friendList)
                    {
                        @if (item.User.ProfileImage == null)
                        {
                            <a asp-controller="Relations" asp-action="UserProfile" asp-route-id="@item.User.Id">
                                <img src="~/Profile/blankProfile.jpg" alt="img" class="smallimg" />
                                @Html.DisplayFor(modelItem => item.User.Firstname)
                                @Html.DisplayFor(x => item.User.Lastname)
                            </a>
                        }
                        else
                        {
                        <a asp-controller="Relations" asp-action="UserProfile" asp-route-id="@item.User.Id">
                            <img src=" @item.User.ProfileImage" alt="img" class="smallimg" />
                            @Html.DisplayFor(modelItem => item.User.Firstname)
                            @Html.DisplayFor(x => item.User.Lastname)
                        </a>
                            }

                        }

                    @foreach (var item in Model.friendList2)
                    {
                        @if (item.Friend.ProfileImage == null)
                        {
                            <a asp-controller="Relations" asp-action="UserProfile" asp-route-id="@item.Friend.Id">
                                <img src="~/Profile/blankProfile.jpg" alt="img" class="smallimg" />
                                @Html.DisplayFor(modelItem => item.Friend.Firstname)
                                @Html.DisplayFor(x => item.Friend.Lastname)
                            </a>
                        }
                        else
                        {
                        <a asp-controller="Relations" asp-action="UserProfile" asp-route-id="@item.Friend.Id">
                            <img src=" @item.Friend.ProfileImage" alt="img" class="smallimg" />
                            @Html.DisplayFor(modelItem => item.Friend.Firstname)
                            @Html.DisplayFor(x => item.Friend.Lastname)
                        </a>
                            }
                        }

                    @foreach (var item in Model.friendList3)
                    {
                        @if (item.Friend.ProfileImage == null)
                        {
                            <a asp-controller="Relations" asp-action="UserProfile" asp-route-id="@item.Friend.Id">
                                <img src="~/Profile/blankProfile.jpg" alt="img" class="smallimg" />
                                @Html.DisplayFor(modelItem => item.Friend.Firstname)
                                @Html.DisplayFor(x => item.Friend.Lastname)
                            </a>
                        }
                        else
                        {
                        <a asp-controller="Relations" asp-action="UserProfile" asp-route-id="@item.Friend.Id">
                            <img src=" @item.Friend.ProfileImage" alt="img" class="smallimg" />
                            @Html.DisplayFor(modelItem => item.Friend.Firstname)
                            @Html.DisplayFor(x => item.Friend.Lastname)
                        </a>
                            }
                        }

                    @foreach (var item in Model.friendList4)
                    {
                        @if (item.User.ProfileImage == null)
                        {
                            <a asp-controller="Relations" asp-action="UserProfile" asp-route-id="@item.User.Id">
                                <img src="~/Profile/blankProfile.jpg" alt="img" class="smallimg" />
                                @Html.DisplayFor(modelItem => item.User.Firstname)
                                @Html.DisplayFor(x => item.User.Lastname)
                            </a>
                        }
                        else
                        {
                        <a asp-controller="Relations" asp-action="UserProfile" asp-route-id="@item.User.Id">
                            <img src=" @item.User.ProfileImage" alt="img" class="smallimg" />
                            @Html.DisplayFor(modelItem => item.User.Firstname)
                            @Html.DisplayFor(x => item.User.Lastname)
                        </a>
                            }
                        }

                </div>

            </div>
        </div>
        <br />
        <hr />

        <div class="col-md-3">
            <h3>Threads Created</h3>
            <ul>
                @foreach (var item in Model.totalThreads)
                {
                    <li><a asp-controller="ThreadPosts" asp-action="Index" asp-route-id="@item.ThreadId">@item.Title</a></li>
                }
            </ul>
        </div>

        <div class="col-md-3">
            <h3>Total Replies</h3>
            <span>@Model.totalPosts.Count()</span>
        </div>

    </div>
    
</div>