ChatItUp/Models/Thread.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ChatItUp.Models
{
    public class Thread
    {
        [Key]
        public int ThreadId { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        [Display(Name = "Message")]
        public string AuthorMessage { get; set; }

        [Required]
        public ApplicationUser User { get; set; }

        [Required]
        public int ForumId { get; set; }
        public Forum Forum { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime created { get; set; }

        public ICollection<ThreadPost> ThreadPost { get; set; }
    }
}

ChatItUp/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ChatItUp.Data;
using ChatItUp.Models;

namespace ChatItUp.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Category.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .SingleOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryId")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category.SingleOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CategoryId")] Category category)
        {
            if (id != category.CategoryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CategoryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .SingleOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Category.SingleOrDefaultAsync(m => m.CategoryId == id);
            _context.Category.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool CategoryExists(int id)
        {
            return _context.Category.Any(e => e.CategoryId == id);
        }
    }
}

ChatItUp/Controllers/ForaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ChatItUp.Data;
using ChatItUp.Models;
using Microsoft.AspNetCore.Identity;

namespace ChatItUp.Controllers
{
    public class ForaController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ForaController(ApplicationDbContext context, UserManager<ApplicationUser> user)
        {
            _context = context;
            _userManager = user;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);
        // GET: Fora
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Forum.Include(f => f.Category);
            return View(await applicationDbContext.ToListAsync());
        }

        //GET: Forum/index/5
        public async Task<IActionResult> Index2(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var currentUser = await GetCurrentUserAsync();
            var forum = await _context.Forum.Where(f => f.CategoryId == id).ToListAsync();
            if(forum == null)
            {
                return NotFound();
            }
            return View(forum);
        }

        // GET: Fora/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forum = await _context.Forum
                .Include(f => f.Category)
                .SingleOrDefaultAsync(m => m.ForumId == id);
            if (forum == null)
            {
                return NotFound();
            }

            return View(forum);
        }

        // GET: Fora/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryId");
            return View();
        }

        // POST: Fora/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ForumId,ThreadTitles,CategoryId")] Forum forum)
        {
            if (ModelState.IsValid)
            {
                _context.Add(forum);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryId", forum.CategoryId);
            return View(forum);
        }

        // GET: Fora/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forum = await _context.Forum.SingleOrDefaultAsync(m => m.ForumId == id);
            if (forum == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryId", forum.CategoryId);
            return View(forum);
        }

        // POST: Fora/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ForumId,ThreadTitles,CategoryId")] Forum forum)
        {
            if (id != forum.ForumId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(forum);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ForumExists(forum.ForumId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryId", forum.CategoryId);
            return View(forum);
        }

        // GET: Fora/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var forum = await _context.Forum
                .Include(f => f.Category)
                .SingleOrDefaultAsync(m => m.ForumId == id);
            if (forum == null)
            {
                return NotFound();
            }

            return View(forum);
        }

        // POST: Fora/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var forum = await _context.Forum.SingleOrDefaultAsync(m => m.ForumId == id);
            _context.Forum.Remove(forum);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool ForumExists(int id)
        {
            return _context.Forum.Any(e => e.ForumId == id);
        }
    }
}

ChatItUp/Controllers/ThreadPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ChatItUp.Data;
using ChatItUp.Models;
using Microsoft.AspNetCore.Identity;
using ChatItUp.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace ChatItUp.Controllers
{
    public class ThreadPostsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ThreadPostsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: ThreadPosts
        public async Task<IActionResult> Index(int? id)
        {
            ThreadPostIndexViewModel ThreadPostVM = new ThreadPostIndexViewModel();

            if(id == null)
            {
                return NotFound();
            }
            ThreadPostVM.threadpost = await _context.ThreadPost.Include(t => t.Thread).Include(u => u.user).Where(tp => tp.ThreadId == (int)id).ToListAsync();

            ThreadPostVM.Thread =  _context.Thread.Include(t => t.ThreadPost).Include(u => u.User).SingleOrDefault(tp => tp.ThreadId == (int)id);


            ThreadPostVM.Forum = _context.Forum.Include(t => t.thread).SingleOrDefault(m => m.ForumId == ThreadPostVM.Thread.ForumId);
            

            return View(ThreadPostVM);
        }

        // GET: ThreadPosts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var threadPost = await _context.ThreadPost
                .Include(t => t.Thread)
                .SingleOrDefaultAsync(m => m.ThreadPostId == id);
            if (threadPost == null)
            {
                return NotFound();
            }

            return View(threadPost);
        }

        // GET: ThreadPosts/Create
        [Authorize]
        public async Task<IActionResult> Create(int? id)
        {
            var threadpost = new ThreadPost();
            threadpost.ThreadId = (int)id;

            var thread= await _context.Thread
                .Where(t => t.ThreadId == threadpost.ThreadId).ToListAsync();

            var user = await GetCurrentUserAsync();
            ViewData["ThreadId"] = new SelectList(_context.Thread, "ThreadId", "ThreadId");
            return View(threadpost);
        }

        // POST: ThreadPosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create(ThreadPost threadPost)
        {
            ModelState.Remove("User");
            if (ModelState.IsValid)
            {
                var user = await GetCurrentUserAsync();
                threadPost.user = user;
                _context.Add(threadPost);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { id = threadPost.ThreadId});
            }
            ViewData["ThreadId"] = new SelectList(_context.Thread, "ThreadId", "ThreadId", threadPost.ThreadId);
            return View(threadPost);
        }

        // GET: ThreadPosts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var threadPost = await _context.ThreadPost.SingleOrDefaultAsync(m => m.ThreadPostId == id);
            if (threadPost == null)
            {
                return NotFound();
            }
            ViewData["ThreadId"] = new SelectList(_context.Thread, "ThreadId", "ThreadId", threadPost.ThreadId);
            return View(threadPost);
        }

        // POST: ThreadPosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ThreadPostId,message,dateCreatd,ThreadId")] ThreadPost threadPost)
        {
            if (id != threadPost.ThreadPostId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(threadPost);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ThreadPostExists(threadPost.ThreadPostId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["ThreadId"] = new SelectList(_context.Thread, "ThreadId", "ThreadId", threadPost.ThreadId);
            return View(threadPost);
        }

        // GET: ThreadPosts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var threadPost = await _context.ThreadPost
                .Include(t => t.Thread)
                .SingleOrDefaultAsync(m => m.ThreadPostId == id);
            if (threadPost == null)
            {
                return NotFound();
            }

            return View(threadPost);
        }

        // POST: ThreadPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var threadPost = await _context.ThreadPost.SingleOrDefaultAsync(m => m.ThreadPostId == id);
            _context.ThreadPost.Remove(threadPost);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool ThreadPostExists(int id)
        {
            return _context.ThreadPost.Any(e => e.ThreadPostId == id);
        }
    }
}

ChatItUp/Views/Threads/Create.cshtml
@model ChatItUp.Models.Thread

@{
    ViewData["Title"] = "Create";
}

<h2>New Thread</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Thread</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Title" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
        </div>

        <input type="hidden" asp-for="ForumId"/>

        <div class="form-group">
            <label asp-for="AuthorMessage" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <textarea asp-for="AuthorMessage" class="form-control"></textarea>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ChatItUp/Views/Threads/Delete.cshtml
@model ChatItUp.Models.Thread

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Thread</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="ThreadId" />
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.created)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.created)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Forum)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Forum.ForumId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

ChatItUp/Views/Threads/Details.cshtml
@model ChatItUp.Models.Thread

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Thread</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.created)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.created)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Forum)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Forum.ForumId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ThreadId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ChatItUp/Views/Threads/Edit.cshtml
@model ChatItUp.Models.Thread

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Thread</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="ThreadId" />
        <div class="form-group">
            <label asp-for="Title" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ForumId" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="ForumId" class="form-control" asp-items="ViewBag.ForumId"></select>
                <span asp-validation-for="ForumId" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="created" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="created" class="form-control" />
                <span asp-validation-for="created" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ChatItUp/Views/Threads/Index.cshtml
@model ChatItUp.Models.ViewModels.ThreadForumViewModel

@{
    ViewData["Title"] = "Index";
}

<h2>Threads</h2>

<p><a asp-controller="Categories" asp-action="Index">Categories </a>: <a asp-controller="Fora" asp-action="Index2" asp-route-id="@Model.Forum.CategoryId">Forum</a> : Threads :</p>
@if(Model.Thread.Count()== 0)
{
    <h3>Be the first to make a thread!</h3>
}

<p>
    <a asp-action="Create" asp-route-id="@Model.Forum.ForumId">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    <span>Title</span>
                </th>
                <th>
                    <span>Created</span>
                </th>
            <th>
                <span>Author</span>
            </th>
            <th>Forum</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Thread) {
        <tr>
            <td>
                <a asp-controller="ThreadPosts" asp-action="Index" asp-route-id="@item.ThreadId">
                @Html.DisplayFor(modelItem => item.Title)
                    </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.created)
            </td>
            <td>
                <span>
                    By:
                    @Html.DisplayFor(modelItem => item.User.Firstname)
                    @Html.DisplayFor(modelItem => item.User.Lastname)
                </span>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Forum.ThreadTitles)
            </td>

        </tr>
}
    </tbody>
</table>